version: "3.3"
   
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: d-docker-web
    container_name: d-docker-web
    entrypoint: /src/docker-entrypoint.sh
    ports:
      - "5000:8000"
    # attach docker sock to interact with the host docker
    volumes: 
      - ./src:/src
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
  
  redis:
    image: redis:alpine
    container_name: d-docker-redis
